<script lang="ts">
  import { invoke } from '@tauri-apps/api/core'; import { listen } from '@tauri-apps/api/event'; import { onMount } from 'svelte';
  import { chooseDirectory, formatBytes, type DuplicateScanComplete, type FileJobProgress } from '../fileTools'; import { copyText } from '../tools';
  let sourceDir=$state('');let recursive=$state(false);let includeZeroByte=$state(false);let jobId=$state('');let progress=$state<FileJobProgress|null>(null);let result=$state<DuplicateScanComplete|null>(null);let message=$state('');let starting=$state(false);let earlyResult:DuplicateScanComplete|null=null;
  let scanning=$derived(!!jobId||starting);
  onMount(()=>{let offProgress:(()=>void)|undefined;let offComplete:(()=>void)|undefined;(async()=>{
    offProgress=await listen<FileJobProgress>('file-tool-progress',e=>{if(e.payload.jobId===jobId)progress=e.payload});
    offComplete=await listen<DuplicateScanComplete>('duplicate-scan-complete',e=>{if(starting&&!jobId){earlyResult=e.payload;return}if(e.payload.jobId!==jobId)return;finish(e.payload)});
  })();return()=>{offProgress?.();offComplete?.()}});
  async function pick(){const value=await chooseDirectory('选择重复文件扫描目录');if(value){sourceDir=value;result=null;message=''}}
  function finish(value:DuplicateScanComplete){result=value;message=value.cancelled?'扫描已取消':`扫描完成：发现 ${value.groups.length} 组重复文件`;jobId=''}
  function takeEarlyResult(){return earlyResult}
  async function start(){result=null;progress=null;message='正在枚举文件…';starting=true;earlyResult=null;try{jobId=await invoke<string>('start_duplicate_scan',{request:{sourceDir,recursive,includeZeroByte}});const completed=takeEarlyResult();if(completed?.jobId===jobId)finish(completed)}catch(e){message=String(e);jobId=''}finally{starting=false}}
  async function cancel(){if(jobId)await invoke('cancel_file_job',{jobId})}
</script>
<div class="tool"><header><div><p>只读安全扫描</p><h2>重复文件扫描</h2></div><span>不会删除任何文件</span></header>
  <section class="source"><input readonly value={sourceDir} placeholder="请选择扫描目录"/><button onclick={pick} disabled={scanning}>选择目录</button><label><input type="checkbox" bind:checked={recursive} disabled={scanning}/>递归子目录</label><label><input type="checkbox" bind:checked={includeZeroByte} disabled={scanning}/>包含零字节文件</label></section>
  <section class="algorithm"><div><strong>分阶段 BLAKE3</strong><small>文件大小 → 首尾 64KiB → 完整文件流式哈希</small></div>{#if scanning}<button class="cancel" onclick={cancel}>取消扫描</button>{:else}<button class="start" disabled={!sourceDir} onclick={start}>开始扫描</button>{/if}</section>
  {#if progress}<div class="progress"><div class="bar"><i style:width={`${progress.totalFiles ? progress.processedFiles/progress.totalFiles*100 : 0}%`}></i></div><span>{progress.stage==='sample'?'快速采样':'完整哈希'} {progress.processedFiles}/{progress.totalFiles} · {formatBytes(progress.processedBytes)}/{formatBytes(progress.totalBytes)} · 错误 {progress.errorCount}</span></div>{/if}
  {#if message}<p class="message">{message}</p>{/if}
  {#if result}<div class="summary"><div><small>扫描文件</small><strong>{result.scannedFiles}</strong></div><div><small>重复组</small><strong>{result.groups.length}</strong></div><div><small>可释放空间</small><strong>{formatBytes(result.reclaimableBytes)}</strong></div><div><small>读取错误</small><strong>{result.errors.length}</strong></div></div>
    <div class="results">{#each result.groups as group,index (group.hash)}<details open={index<3}><summary><strong>{group.paths.length} 个相同文件 · {formatBytes(group.size)}</strong><span>可释放 {formatBytes(group.reclaimableBytes)}</span></summary>{#each group.paths as path}<div class="path"><code title={path}>{path}</code><button onclick={()=>copyText(path)}>复制</button></div>{/each}</details>{/each}{#if !result.groups.length}<div class="empty">没有发现重复文件。</div>{/if}</div>
    {#if result.errors.length}<details class="errors"><summary>无法读取的文件（{result.errors.length}）</summary>{#each result.errors as error}<code>{error}</code>{/each}</details>{/if}
  {/if}
</div>
<style>
  .tool{height:100%;display:flex;flex-direction:column;gap:14px;overflow:auto;padding:2px}header,.source,.algorithm,.summary,.path,details summary{display:flex;align-items:center;gap:10px}header{justify-content:space-between}header p,small,.progress span{color:var(--text-secondary);font-size:12px}h2{font-size:24px}header>span{color:#16a085;background:rgba(22,160,133,.12);padding:6px 10px;border-radius:999px}.source,.algorithm{padding:12px;border:1px solid var(--border-subtle);border-radius:12px;background:var(--bg-panel0)}.source>input{flex:1}.source label{display:flex;gap:5px;font-size:12px}.algorithm{justify-content:space-between}.algorithm small{display:block;margin-top:3px}.start{background:#3b82f6!important;color:white!important}.cancel{color:#e74c3c!important}.bar{height:7px;background:var(--bg-panel1);border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:#3b82f6}.progress span{display:block;margin-top:5px}.message{font-size:13px}.summary{display:grid;grid-template-columns:repeat(4,1fr)}.summary>div{padding:12px;border-radius:12px;background:var(--bg-panel1)}.summary strong,.summary small{display:block}.summary strong{font-size:20px;margin-top:4px}.results{display:flex;flex-direction:column;gap:8px;overflow:auto}.results details,.errors{border:1px solid var(--border-subtle);border-radius:10px;padding:10px}.results summary{justify-content:space-between;cursor:pointer}.path{margin-top:7px}.path code{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.path button{padding:4px 8px}.errors code{display:block;color:#e74c3c;font-size:11px;margin-top:5px}.empty{text-align:center;color:var(--text-secondary);padding:28px}input,button{border:1px solid var(--border-subtle);border-radius:8px;padding:7px 9px;background:var(--bg-panel1);color:var(--text-primary)}button{cursor:pointer}button:disabled{opacity:.45}
</style>
